version: '3.8'

services:
  web:
    container_name: metropole4_webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - POSTGRES_URL_NON_POOLING=postgresql://johndoe:devPassword@db:5432/metropole4_db
    entrypoint: [ "/wait-for-it.sh", "db:5432", "--", "sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm run build && npm run start" ]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: devPassword
      POSTGRES_DB: metropole4_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
